name:                overeasy
version:             0.1.0
github:              "ejconlon/overeasy"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2021 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/overeasy#readme>

dependencies:
- base >= 4.12 && < 5
- algebraic-graphs
- containers
- data-fix
- deepseq
- hashable
- mtl
- recursion-schemes
- text
- transformers
- unordered-containers

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- PatternSynonyms
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

tests:
  overeasy-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - overeasy
    - hedgehog
    - pretty-simple
    - tasty
    - tasty-hedgehog
