allow-newer: true
resolver: 
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/nightly/2022/4/28.yaml


ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- git: git@github.com:Tarmean/int-like.git
  commit: c636f81c33367d69f6202a0f16553df2b858f412
- git: git@github.com:ejconlon/prop-unit.git
  commit: 167f919ee66dc2f6f17b9ad952be3921779789ea
