allow-newer: true
resolver: 
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/nightly/2022/4/28.yaml


ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- git: git@github.com:Tarmean/int-like.git
  commit: 79e475d4154435165027002bfff371b8b6f834c6
- git: git@github.com:ejconlon/prop-unit.git
  commit: 167f919ee66dc2f6f17b9ad952be3921779789ea
