resolver: lts-18.21

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- git: git@github.com:ejconlon/int-like.git
  commit: e814624a26d71f02582e5cb9ea0955aa721d509e
- git: git@github.com:ejconlon/prop-unit.git
  commit: 167f919ee66dc2f6f17b9ad952be3921779789ea
